// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/kafka/protobuf/CrazyCricketProtos.proto

package pojo;

public final class CrazyCricketProtos {
  private CrazyCricketProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Player winner = 1;
    /**
     * <code>required .Player winner = 1;</code>
     */
    boolean hasWinner();
    /**
     * <code>required .Player winner = 1;</code>
     */
    pojo.CrazyCricketProtos.Player getWinner();
    /**
     * <code>required .Player winner = 1;</code>
     */
    pojo.CrazyCricketProtos.PlayerOrBuilder getWinnerOrBuilder();

    // required .Player loser = 2;
    /**
     * <code>required .Player loser = 2;</code>
     */
    boolean hasLoser();
    /**
     * <code>required .Player loser = 2;</code>
     */
    pojo.CrazyCricketProtos.Player getLoser();
    /**
     * <code>required .Player loser = 2;</code>
     */
    pojo.CrazyCricketProtos.PlayerOrBuilder getLoserOrBuilder();

    // required .Game.GameType type = 3;
    /**
     * <code>required .Game.GameType type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>required .Game.GameType type = 3;</code>
     */
    pojo.CrazyCricketProtos.Game.GameType getType();

    // required int64 gameDate = 4;
    /**
     * <code>required int64 gameDate = 4;</code>
     */
    boolean hasGameDate();
    /**
     * <code>required int64 gameDate = 4;</code>
     */
    long getGameDate();
  }
  /**
   * Protobuf type {@code Game}
   */
  public static final class Game extends
      com.google.protobuf.GeneratedMessage
      implements GameOrBuilder {
    // Use Game.newBuilder() to construct.
    private Game(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Game(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Game defaultInstance;
    public static Game getDefaultInstance() {
      return defaultInstance;
    }

    public Game getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Game(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              pojo.CrazyCricketProtos.Player.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = winner_.toBuilder();
              }
              winner_ = input.readMessage(pojo.CrazyCricketProtos.Player.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(winner_);
                winner_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              pojo.CrazyCricketProtos.Player.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = loser_.toBuilder();
              }
              loser_ = input.readMessage(pojo.CrazyCricketProtos.Player.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loser_);
                loser_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              pojo.CrazyCricketProtos.Game.GameType value = pojo.CrazyCricketProtos.Game.GameType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              gameDate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pojo.CrazyCricketProtos.internal_static_Game_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pojo.CrazyCricketProtos.internal_static_Game_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pojo.CrazyCricketProtos.Game.class, pojo.CrazyCricketProtos.Game.Builder.class);
    }

    public static com.google.protobuf.Parser<Game> PARSER =
        new com.google.protobuf.AbstractParser<Game>() {
      public Game parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Game(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Game> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Game.GameType}
     */
    public enum GameType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEST = 0;</code>
       */
      TEST(0, 0),
      /**
       * <code>LIMITED_OVERS = 1;</code>
       */
      LIMITED_OVERS(1, 1),
      /**
       * <code>TWENTY_TWENTY = 2;</code>
       */
      TWENTY_TWENTY(2, 2),
      /**
       * <code>OTHER = 3;</code>
       */
      OTHER(3, 3),
      ;

      /**
       * <code>TEST = 0;</code>
       */
      public static final int TEST_VALUE = 0;
      /**
       * <code>LIMITED_OVERS = 1;</code>
       */
      public static final int LIMITED_OVERS_VALUE = 1;
      /**
       * <code>TWENTY_TWENTY = 2;</code>
       */
      public static final int TWENTY_TWENTY_VALUE = 2;
      /**
       * <code>OTHER = 3;</code>
       */
      public static final int OTHER_VALUE = 3;


      public final int getNumber() { return value; }

      public static GameType valueOf(int value) {
        switch (value) {
          case 0: return TEST;
          case 1: return LIMITED_OVERS;
          case 2: return TWENTY_TWENTY;
          case 3: return OTHER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<GameType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<GameType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<GameType>() {
              public GameType findValueByNumber(int number) {
                return GameType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pojo.CrazyCricketProtos.Game.getDescriptor().getEnumTypes().get(0);
      }

      private static final GameType[] VALUES = values();

      public static GameType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private GameType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Game.GameType)
    }

    private int bitField0_;
    // required .Player winner = 1;
    public static final int WINNER_FIELD_NUMBER = 1;
    private pojo.CrazyCricketProtos.Player winner_;
    /**
     * <code>required .Player winner = 1;</code>
     */
    public boolean hasWinner() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Player winner = 1;</code>
     */
    public pojo.CrazyCricketProtos.Player getWinner() {
      return winner_;
    }
    /**
     * <code>required .Player winner = 1;</code>
     */
    public pojo.CrazyCricketProtos.PlayerOrBuilder getWinnerOrBuilder() {
      return winner_;
    }

    // required .Player loser = 2;
    public static final int LOSER_FIELD_NUMBER = 2;
    private pojo.CrazyCricketProtos.Player loser_;
    /**
     * <code>required .Player loser = 2;</code>
     */
    public boolean hasLoser() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Player loser = 2;</code>
     */
    public pojo.CrazyCricketProtos.Player getLoser() {
      return loser_;
    }
    /**
     * <code>required .Player loser = 2;</code>
     */
    public pojo.CrazyCricketProtos.PlayerOrBuilder getLoserOrBuilder() {
      return loser_;
    }

    // required .Game.GameType type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private pojo.CrazyCricketProtos.Game.GameType type_;
    /**
     * <code>required .Game.GameType type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .Game.GameType type = 3;</code>
     */
    public pojo.CrazyCricketProtos.Game.GameType getType() {
      return type_;
    }

    // required int64 gameDate = 4;
    public static final int GAMEDATE_FIELD_NUMBER = 4;
    private long gameDate_;
    /**
     * <code>required int64 gameDate = 4;</code>
     */
    public boolean hasGameDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 gameDate = 4;</code>
     */
    public long getGameDate() {
      return gameDate_;
    }

    private void initFields() {
      winner_ = pojo.CrazyCricketProtos.Player.getDefaultInstance();
      loser_ = pojo.CrazyCricketProtos.Player.getDefaultInstance();
      type_ = pojo.CrazyCricketProtos.Game.GameType.TEST;
      gameDate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasWinner()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLoser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGameDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getWinner().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getLoser().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, winner_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, loser_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, gameDate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, winner_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, loser_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, gameDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pojo.CrazyCricketProtos.Game parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pojo.CrazyCricketProtos.Game parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pojo.CrazyCricketProtos.Game parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pojo.CrazyCricketProtos.Game parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pojo.CrazyCricketProtos.Game parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pojo.CrazyCricketProtos.Game parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pojo.CrazyCricketProtos.Game parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pojo.CrazyCricketProtos.Game parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pojo.CrazyCricketProtos.Game parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pojo.CrazyCricketProtos.Game parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pojo.CrazyCricketProtos.Game prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Game}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pojo.CrazyCricketProtos.GameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pojo.CrazyCricketProtos.internal_static_Game_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pojo.CrazyCricketProtos.internal_static_Game_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pojo.CrazyCricketProtos.Game.class, pojo.CrazyCricketProtos.Game.Builder.class);
      }

      // Construct using pojo.CrazyCricketProtos.Game.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWinnerFieldBuilder();
          getLoserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (winnerBuilder_ == null) {
          winner_ = pojo.CrazyCricketProtos.Player.getDefaultInstance();
        } else {
          winnerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (loserBuilder_ == null) {
          loser_ = pojo.CrazyCricketProtos.Player.getDefaultInstance();
        } else {
          loserBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = pojo.CrazyCricketProtos.Game.GameType.TEST;
        bitField0_ = (bitField0_ & ~0x00000004);
        gameDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pojo.CrazyCricketProtos.internal_static_Game_descriptor;
      }

      public pojo.CrazyCricketProtos.Game getDefaultInstanceForType() {
        return pojo.CrazyCricketProtos.Game.getDefaultInstance();
      }

      public pojo.CrazyCricketProtos.Game build() {
        pojo.CrazyCricketProtos.Game result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pojo.CrazyCricketProtos.Game buildPartial() {
        pojo.CrazyCricketProtos.Game result = new pojo.CrazyCricketProtos.Game(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (winnerBuilder_ == null) {
          result.winner_ = winner_;
        } else {
          result.winner_ = winnerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (loserBuilder_ == null) {
          result.loser_ = loser_;
        } else {
          result.loser_ = loserBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gameDate_ = gameDate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pojo.CrazyCricketProtos.Game) {
          return mergeFrom((pojo.CrazyCricketProtos.Game)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pojo.CrazyCricketProtos.Game other) {
        if (other == pojo.CrazyCricketProtos.Game.getDefaultInstance()) return this;
        if (other.hasWinner()) {
          mergeWinner(other.getWinner());
        }
        if (other.hasLoser()) {
          mergeLoser(other.getLoser());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasGameDate()) {
          setGameDate(other.getGameDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWinner()) {
          
          return false;
        }
        if (!hasLoser()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasGameDate()) {
          
          return false;
        }
        if (!getWinner().isInitialized()) {
          
          return false;
        }
        if (!getLoser().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pojo.CrazyCricketProtos.Game parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pojo.CrazyCricketProtos.Game) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Player winner = 1;
      private pojo.CrazyCricketProtos.Player winner_ = pojo.CrazyCricketProtos.Player.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pojo.CrazyCricketProtos.Player, pojo.CrazyCricketProtos.Player.Builder, pojo.CrazyCricketProtos.PlayerOrBuilder> winnerBuilder_;
      /**
       * <code>required .Player winner = 1;</code>
       */
      public boolean hasWinner() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Player winner = 1;</code>
       */
      public pojo.CrazyCricketProtos.Player getWinner() {
        if (winnerBuilder_ == null) {
          return winner_;
        } else {
          return winnerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Player winner = 1;</code>
       */
      public Builder setWinner(pojo.CrazyCricketProtos.Player value) {
        if (winnerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          winner_ = value;
          onChanged();
        } else {
          winnerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Player winner = 1;</code>
       */
      public Builder setWinner(
          pojo.CrazyCricketProtos.Player.Builder builderForValue) {
        if (winnerBuilder_ == null) {
          winner_ = builderForValue.build();
          onChanged();
        } else {
          winnerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Player winner = 1;</code>
       */
      public Builder mergeWinner(pojo.CrazyCricketProtos.Player value) {
        if (winnerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              winner_ != pojo.CrazyCricketProtos.Player.getDefaultInstance()) {
            winner_ =
              pojo.CrazyCricketProtos.Player.newBuilder(winner_).mergeFrom(value).buildPartial();
          } else {
            winner_ = value;
          }
          onChanged();
        } else {
          winnerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Player winner = 1;</code>
       */
      public Builder clearWinner() {
        if (winnerBuilder_ == null) {
          winner_ = pojo.CrazyCricketProtos.Player.getDefaultInstance();
          onChanged();
        } else {
          winnerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Player winner = 1;</code>
       */
      public pojo.CrazyCricketProtos.Player.Builder getWinnerBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getWinnerFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Player winner = 1;</code>
       */
      public pojo.CrazyCricketProtos.PlayerOrBuilder getWinnerOrBuilder() {
        if (winnerBuilder_ != null) {
          return winnerBuilder_.getMessageOrBuilder();
        } else {
          return winner_;
        }
      }
      /**
       * <code>required .Player winner = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pojo.CrazyCricketProtos.Player, pojo.CrazyCricketProtos.Player.Builder, pojo.CrazyCricketProtos.PlayerOrBuilder> 
          getWinnerFieldBuilder() {
        if (winnerBuilder_ == null) {
          winnerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pojo.CrazyCricketProtos.Player, pojo.CrazyCricketProtos.Player.Builder, pojo.CrazyCricketProtos.PlayerOrBuilder>(
                  winner_,
                  getParentForChildren(),
                  isClean());
          winner_ = null;
        }
        return winnerBuilder_;
      }

      // required .Player loser = 2;
      private pojo.CrazyCricketProtos.Player loser_ = pojo.CrazyCricketProtos.Player.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pojo.CrazyCricketProtos.Player, pojo.CrazyCricketProtos.Player.Builder, pojo.CrazyCricketProtos.PlayerOrBuilder> loserBuilder_;
      /**
       * <code>required .Player loser = 2;</code>
       */
      public boolean hasLoser() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Player loser = 2;</code>
       */
      public pojo.CrazyCricketProtos.Player getLoser() {
        if (loserBuilder_ == null) {
          return loser_;
        } else {
          return loserBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Player loser = 2;</code>
       */
      public Builder setLoser(pojo.CrazyCricketProtos.Player value) {
        if (loserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loser_ = value;
          onChanged();
        } else {
          loserBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Player loser = 2;</code>
       */
      public Builder setLoser(
          pojo.CrazyCricketProtos.Player.Builder builderForValue) {
        if (loserBuilder_ == null) {
          loser_ = builderForValue.build();
          onChanged();
        } else {
          loserBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Player loser = 2;</code>
       */
      public Builder mergeLoser(pojo.CrazyCricketProtos.Player value) {
        if (loserBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              loser_ != pojo.CrazyCricketProtos.Player.getDefaultInstance()) {
            loser_ =
              pojo.CrazyCricketProtos.Player.newBuilder(loser_).mergeFrom(value).buildPartial();
          } else {
            loser_ = value;
          }
          onChanged();
        } else {
          loserBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Player loser = 2;</code>
       */
      public Builder clearLoser() {
        if (loserBuilder_ == null) {
          loser_ = pojo.CrazyCricketProtos.Player.getDefaultInstance();
          onChanged();
        } else {
          loserBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .Player loser = 2;</code>
       */
      public pojo.CrazyCricketProtos.Player.Builder getLoserBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLoserFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Player loser = 2;</code>
       */
      public pojo.CrazyCricketProtos.PlayerOrBuilder getLoserOrBuilder() {
        if (loserBuilder_ != null) {
          return loserBuilder_.getMessageOrBuilder();
        } else {
          return loser_;
        }
      }
      /**
       * <code>required .Player loser = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pojo.CrazyCricketProtos.Player, pojo.CrazyCricketProtos.Player.Builder, pojo.CrazyCricketProtos.PlayerOrBuilder> 
          getLoserFieldBuilder() {
        if (loserBuilder_ == null) {
          loserBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pojo.CrazyCricketProtos.Player, pojo.CrazyCricketProtos.Player.Builder, pojo.CrazyCricketProtos.PlayerOrBuilder>(
                  loser_,
                  getParentForChildren(),
                  isClean());
          loser_ = null;
        }
        return loserBuilder_;
      }

      // required .Game.GameType type = 3;
      private pojo.CrazyCricketProtos.Game.GameType type_ = pojo.CrazyCricketProtos.Game.GameType.TEST;
      /**
       * <code>required .Game.GameType type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .Game.GameType type = 3;</code>
       */
      public pojo.CrazyCricketProtos.Game.GameType getType() {
        return type_;
      }
      /**
       * <code>required .Game.GameType type = 3;</code>
       */
      public Builder setType(pojo.CrazyCricketProtos.Game.GameType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Game.GameType type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = pojo.CrazyCricketProtos.Game.GameType.TEST;
        onChanged();
        return this;
      }

      // required int64 gameDate = 4;
      private long gameDate_ ;
      /**
       * <code>required int64 gameDate = 4;</code>
       */
      public boolean hasGameDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 gameDate = 4;</code>
       */
      public long getGameDate() {
        return gameDate_;
      }
      /**
       * <code>required int64 gameDate = 4;</code>
       */
      public Builder setGameDate(long value) {
        bitField0_ |= 0x00000008;
        gameDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 gameDate = 4;</code>
       */
      public Builder clearGameDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gameDate_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Game)
    }

    static {
      defaultInstance = new Game(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Game)
  }

  public interface PlayerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string userId = 1;
    /**
     * <code>required string userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>required string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    // required string country = 2;
    /**
     * <code>required string country = 2;</code>
     */
    boolean hasCountry();
    /**
     * <code>required string country = 2;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>required string country = 2;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();
  }
  /**
   * Protobuf type {@code Player}
   */
  public static final class Player extends
      com.google.protobuf.GeneratedMessage
      implements PlayerOrBuilder {
    // Use Player.newBuilder() to construct.
    private Player(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Player(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Player defaultInstance;
    public static Player getDefaultInstance() {
      return defaultInstance;
    }

    public Player getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Player(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              country_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pojo.CrazyCricketProtos.internal_static_Player_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pojo.CrazyCricketProtos.internal_static_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pojo.CrazyCricketProtos.Player.class, pojo.CrazyCricketProtos.Player.Builder.class);
    }

    public static com.google.protobuf.Parser<Player> PARSER =
        new com.google.protobuf.AbstractParser<Player>() {
      public Player parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Player(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Player> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    /**
     * <code>required string userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string country = 2;
    public static final int COUNTRY_FIELD_NUMBER = 2;
    private java.lang.Object country_;
    /**
     * <code>required string country = 2;</code>
     */
    public boolean hasCountry() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string country = 2;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          country_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string country = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userId_ = "";
      country_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCountry()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCountryBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCountryBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pojo.CrazyCricketProtos.Player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pojo.CrazyCricketProtos.Player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pojo.CrazyCricketProtos.Player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pojo.CrazyCricketProtos.Player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pojo.CrazyCricketProtos.Player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pojo.CrazyCricketProtos.Player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pojo.CrazyCricketProtos.Player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pojo.CrazyCricketProtos.Player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pojo.CrazyCricketProtos.Player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pojo.CrazyCricketProtos.Player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pojo.CrazyCricketProtos.Player prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Player}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pojo.CrazyCricketProtos.PlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pojo.CrazyCricketProtos.internal_static_Player_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pojo.CrazyCricketProtos.internal_static_Player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pojo.CrazyCricketProtos.Player.class, pojo.CrazyCricketProtos.Player.Builder.class);
      }

      // Construct using pojo.CrazyCricketProtos.Player.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        country_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pojo.CrazyCricketProtos.internal_static_Player_descriptor;
      }

      public pojo.CrazyCricketProtos.Player getDefaultInstanceForType() {
        return pojo.CrazyCricketProtos.Player.getDefaultInstance();
      }

      public pojo.CrazyCricketProtos.Player build() {
        pojo.CrazyCricketProtos.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pojo.CrazyCricketProtos.Player buildPartial() {
        pojo.CrazyCricketProtos.Player result = new pojo.CrazyCricketProtos.Player(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.country_ = country_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pojo.CrazyCricketProtos.Player) {
          return mergeFrom((pojo.CrazyCricketProtos.Player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pojo.CrazyCricketProtos.Player other) {
        if (other == pojo.CrazyCricketProtos.Player.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          bitField0_ |= 0x00000001;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasCountry()) {
          bitField0_ |= 0x00000002;
          country_ = other.country_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasCountry()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pojo.CrazyCricketProtos.Player parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pojo.CrazyCricketProtos.Player) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string userId = 1;
      private java.lang.Object userId_ = "";
      /**
       * <code>required string userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }

      // required string country = 2;
      private java.lang.Object country_ = "";
      /**
       * <code>required string country = 2;</code>
       */
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string country = 2;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string country = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string country = 2;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string country = 2;</code>
       */
      public Builder clearCountry() {
        bitField0_ = (bitField0_ & ~0x00000002);
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>required string country = 2;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        country_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Player)
    }

    static {
      defaultInstance = new Player(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Player)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Game_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Game_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Player_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Player_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5src/main/java/kafka/protobuf/CrazyCric" +
      "ketProtos.proto\"\256\001\n\004Game\022\027\n\006winner\030\001 \002(\013" +
      "2\007.Player\022\026\n\005loser\030\002 \002(\0132\007.Player\022\034\n\004typ" +
      "e\030\003 \002(\0162\016.Game.GameType\022\020\n\010gameDate\030\004 \002(" +
      "\003\"E\n\010GameType\022\010\n\004TEST\020\000\022\021\n\rLIMITED_OVERS" +
      "\020\001\022\021\n\rTWENTY_TWENTY\020\002\022\t\n\005OTHER\020\003\")\n\006Play" +
      "er\022\016\n\006userId\030\001 \002(\t\022\017\n\007country\030\002 \002(\tB\032\n\004p" +
      "ojoB\022CrazyCricketProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Game_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Game_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Game_descriptor,
              new java.lang.String[] { "Winner", "Loser", "Type", "GameDate", });
          internal_static_Player_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Player_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Player_descriptor,
              new java.lang.String[] { "UserId", "Country", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
